worker_processes auto;
worker_rlimit_nofile 1048576;

events {
  worker_connections 1048576;
  multi_accept on;
  use epoll;
}

http {
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 3600s;
  keepalive_requests 20000;
  client_max_body_size 0;

  grpc_read_timeout 86400s;
  grpc_send_timeout 86400s;
  grpc_connect_timeout 60s;

  server {
    listen 8080 http2;
    listen [::]:8080 http2;

    location / {
      proxy_pass https://www.google.com;
      proxy_set_header Host www.google.com;
      proxy_ssl_server_name on;
    }

    location /JonathanXH {
      grpc_pass grpc://127.0.0.1:12001;
      grpc_set_header X-Real-IP $remote_addr;
      grpc_set_header Host $host;
      grpc_read_timeout 86400s;
      grpc_send_timeout 86400s;
    }
  }
}
